CREATE TABLE IF NOT EXISTS admin (
	id TEXT PRIMARY KEY,
	username TEXT NOT NULL UNIQUE,
	password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS slide_abordagem_cuida (
	id TEXT PRIMARY KEY,
	imagem_url TEXT NOT NULL
);